spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

springdoc:
  swagger-ui:
    enabled: false
